---
collections:
  - name: ansible.posix
    version: 1.5.4
  - name: ansible.utils
    version: 5.0.0
  - name: community.docker
    version: 3.10.3
  - name: community.general
    version: 9.0.1
  - name: community.sops
    version: 1.7.0
  - name: kubernetes.core
    version: 5.0.0
