---
collections:
  - name: ansible.posix
    version: 2.0.0
  - name: ansible.utils
    version: 6.0.0
  - name: bitwarden.secrets
    version: 1.0.1
  - name: community.docker
    version: 4.6.1
  - name: community.general
    version: 11.1.0
