---
collections:
  - name: ansible.posix
    version: 2.0.0
  - name: ansible.utils
    version: 5.1.2
  - name: bitwarden.secrets
    version: 1.0.1
  - name: community.docker
    version: 4.5.2
  - name: community.general
    version: 10.5.0
