---
- name: Kind | Detect previous install
  ansible.builtin.stat:
    path: /usr/local/bin/kind
  register: kind

- name: Kind | Register state
  ansible.builtin.set_fact:
    kind_is_installed: "{{ kind.stat.exists }}"

- name: Fastfetch | Install
  when:
    - not kind_is_installed
  block:
    - name: Kind | Download latest JSON
      ansible.builtin.uri:
        url: https://api.github.com/repos/kubernetes-sigs/kind/releases/latest
      register: kind_latest_version_json
      changed_when: false

    - name: Kind | Registering latest Release
      ansible.builtin.set_fact:
        kind_latest_release: "{{ kind_latest_version_json.json.tag_name }}"

    - name: Kind | Registering latest version
      ansible.builtin.set_fact:
        fastfetch_latest_version: "{{ kind_latest_release.stdout | default('') }}"

    - name: Kind | Show latest release
      ansible.builtin.debug:
        var: kind_latest_release
