---
version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    cooldown:
      default-days: 7
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
    groups:
      github-actions-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      github-actions-major:
        patterns:
          - "*"
        update-types:
          - "major"
  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "pre-commit"
    commit-message:
      prefix: "ci"
    groups:
      pre-commit-all:
        patterns:
          - "*"
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    cooldown:
      default-days: 7
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      python-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      python-major:
        patterns:
          - "*"
        update-types:
          - "major"
