---
- name: Start ntp
  ansible.builtin.service:
    name: ntp
    state: started
- name: Start qemu
  ansible.builtin.service:
    name: qemu-guest-agent
    state: started
- name: Start unattended-upgrades
  ansible.builtin.systemd:
    name: unattended-upgrades
    state: started
- name: Reboot
  ansible.builtin.reboot:
    msg: Rebooting nodes
    reboot_timeout: 3600
    test_command: uptime
- name: Reload cloud-init
  systemd:
    name: cloud-init
    daemon_reload: true
