---
- name: GitHub | Install GitHub CLI tool
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - gh
  become: true

# - name: Authenticate with GitHub using SSH key
#   command: gh auth login --hostname github.com --git-protocol ssh
