---
# Orchestrator only: no module calls other than include_vars / include_tasks.

- name: Helm | Load release specific variables
  ansible.builtin.include_vars: "{{ helm_vars_file }}"
  loop: "{{ query('ansible.builtin.first_found', helm_vars_lookup) }}"
  loop_control:
    loop_var: helm_vars_file
  vars:
    helm_vars_lookup:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - "{{ role_path }}/vars"
      skip: true
  tags:
    - helm
    - k8s

- name: Helm | Install
  ansible.builtin.include_tasks: "{{ helm_install_tasks }}"
  vars:
    helm_install_tasks: "{{ lookup('ansible.builtin.first_found', helm_install_lookup) }}"
    helm_install_lookup:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - "{{ role_path }}/tasks/install"
  tags:
    - helm
    - k8s
    - install

- name: Helm | Verify
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/verify.yml"
  when: not ansible_check_mode
  tags:
    - helm
    - k8s
    - verify
