---
- name: "Helm CLI  | Install dependencies"
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
    state: present
  become: true

- name: Helm | Add Helm GPG key
  ansible.builtin.apt_key:
    url: https://baltocdn.com/helm/signing.asc
    keyring: /usr/share/keyrings/helm.gpg
    state: present
  become: true

- name: "Helm | Get System Architecture"
  ansible.builtin.command: "dpkg --print-architecture"
  register: dpkg_architecture
  changed_when: false
  failed_when: false
  check_mode: false

- name: Helm | Add Helm APT repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ dpkg_architecture.stdout }} signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main"
    filename: helm
  become: true

- name: "Helm | Install Helm Engine"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
      - helm
  become: true
