---
- name: NVM | Install
  block:
    - name: NVM | Download latest JSON
      ansible.builtin.uri:
        url: https://api.github.com/repos/nvm-sh/nvm/releases/latest
      register: nvm_latest_version_json
      changed_when: false

    - name: NVM | Registering latest release
      ansible.builtin.set_fact:
        nvm_latest_release: "{{ nvm_latest_version_json.json.tag_name }}"

    - name: NVM | Show latest release
      ansible.builtin.debug:
        var: nvm_latest_release

    - name: NVM | Install nvm
      ansible.builtin.shell: >
        set -o pipefail && curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/{{ nvm_latest_release }}/install.sh | bash
      args:
        creates: "{{ ansible_home }}/.nvm/nvm.sh"
        executable: /bin/bash
