---
fail_fast: false
ci:
  autoupdate_schedule: monthly
  skip:
    - actionlint
    - ansible-lint
    - ggshield
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.29.1
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.32.1
    hooks:
      - id: ggshield
        language_version: python3
        stages: [pre-commit]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      # Git style
      - id: check-added-large-files
        args: [--maxkb=2048]
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: forbid-new-submodules
      - id: forbid-submodules
      # Common errors
      - id: check-json
      - id: check-yaml
        files: /.(yaml|yml)$
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
      # Cross platform
      - id: check-case-conflict
      - id: mixed-line-ending
        args:
          - --fix=lf
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: remove-crlf
      - id: remove-tabs
  - repo: https://github.com/sirosen/texthooks
    rev: 0.6.7
    hooks:
      - id: alphabetize-codeowners
      - id: fix-smartquotes
      - id: fix-ligatures
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.42.0
    hooks:
      - id: markdownlint
        args:
          - --config
          - .config/.markdown-lint.yml
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args:
          - -c
          - .config/.yaml-lint.yml
  - repo: https://github.com/ansible-community/ansible-lint
    rev: v24.9.2
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
        args:
          - -c
          - .config/.ansible-lint.yml
          - --fix
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.3
    hooks:
      - id: actionlint
