---
exclude: |
  (?x)^(
    \.pre-commit-config\.yaml$
  )
fail_fast: false
default_stages:
  - pre-commit
default_language_version:
  python: python3.12
default_install_hook_types:
  - commit-msg
  - pre-commit
ci:
  skip:
    - ansible-lint
    - ggshield
repos:
  - repo: meta
    hooks:
      - id: identity
        name: "meta | pre-commit hooks"
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.8.3
    hooks:
      - id: commitizen
        name: "git | validate commit messages"
        stages:
          - commit-msg
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.41.0
    hooks:
      - id: ggshield
        name: "security | scan for secrets"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=2048]
        name: "git | block large files"
      - id: check-json
        name: "general | check JSON files"
      - id: check-toml
        name: "general | check TOML files"
      - id: check-xml
        name: "general | check XML files"
      - id: check-yaml
        name: "general | check YAML files"
      - id: end-of-file-fixer
        name: "general | fix end of file"
      - id: forbid-new-submodules
        name: "git | forbid new submodules"
      - id: forbid-submodules
        name: "git | forbid submodules usage"
      - id: mixed-line-ending
        args:
          - --fix=auto
        name: "general | fix line ending"
      - id: no-commit-to-branch
        args:
          - --branch=main
        name: "git | protect main branch"
        stages:
          - manual
      - id: pretty-format-json
        args:
          - --autofix
          - --no-ensure-ascii
        name: "general | prettify JSON files"
      - id: trailing-whitespace
        name: "general | remove trailing whitespace"
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        args:
          - --config
          - .config/.markdown-lint.yml
        name: "md | lint: run markdownlint-cli"
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        args:
          - -c
          - .config/.yaml-lint.yml
        name: "yaml | lint: run yamllint"
  - repo: https://github.com/ansible-community/ansible-lint
    rev: v25.6.1
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
        args:
          - -c
          - .config/.ansible-lint.yml
          - --fix
        name: "ansible | lint: run ansible-lint"
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
        name: "gh-action | lint: run actionlint"
