---
- name: DotFiles Config
  hosts: localhost
  connection: local
  gather_facts: true
  any_errors_fatal: false

  pre_tasks:
    - name: Detect environment
      ansible.builtin.import_tasks: pre_tasks/whoami.yml

  tasks:
    - name: Set roles
      ansible.builtin.set_fact:
        run_roles: "{{ ansible_run_tags != ['all'] and ansible_run_tags or default_roles | difference(exclude_roles | default([])) }}"
    - name: Display roles
      ansible.builtin.debug:
        var: run_roles
    - name: Run roles
      ansible.builtin.include_role:
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ run_roles }}"

  post_tasks:
    - name: Status message
      ansible.builtin.import_tasks: post_tasks/end.yml
