---
- name: DotFiles Config
  hosts: localhost
  connection: local
  gather_facts: true
  any_errors_fatal: false

  pre_tasks:
    - name: Ping machine
      ansible.builtin.ping:

    - name: Show the uptime
      ansible.builtin.debug:
        msg: Uptime {{ now().replace(microsecond=0) - now().fromtimestamp(now(fmt='%s') | int - ansible_uptime_seconds) }}

    - name: Detect WSL
      ansible.builtin.import_tasks: pre_tasks/detect_wsl.yml

    # - name: Confirm Windows PowerShell Execution Policy
    #   ansible.builtin.import_tasks: pre_tasks/powershell_executionpolicy.yml
    #   when: ansible_host_environment_is_wsl

    - name: Detect Host User
      ansible.builtin.import_tasks: pre_tasks/whoami_wsl.yml
      when: ansible_host_environment_is_wsl

    - name: Detect Host User
      ansible.builtin.import_tasks: pre_tasks/whoami.yml

  tasks:
    - name: Set roles
      ansible.builtin.set_fact:
        run_roles: "{{ ansible_run_tags != ['all'] and ansible_run_tags or default_roles | difference(exclude_roles | default([])) }}"

    - name: Display roles
      ansible.builtin.debug:
        var: run_roles

    - name: Run roles
      ansible.builtin.include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ run_roles }}"

  post_tasks:
    - name: Status message
      ansible.builtin.debug:
        msg: Playbook ran without any issue.
