---
- name: DotFiles Config
  hosts: localhost
  connection: local
  gather_facts: true
  any_errors_fatal: false

  pre_tasks:
    - name: Detect environment
      ansible.builtin.import_tasks: pre_tasks/whoami.yml

  tasks:
    - name: Set roles
      block:
        - name: Run roles
          ansible.builtin.include_role:
            name: "{{ item }}"
          with_items:
            - git
            - python
            - system
            - zsh

      rescue:
        - name: Rescue roles | Update
          ansible.builtin.debug:
            msg: Playbook encountered an issue while setting role, only update role will be run.

      always:
        - name: Default roles | Update
          ansible.builtin.include_role:
            name: "{{ item }}"
          with_items:
            - update

  post_tasks:
    - name: Status message
      ansible.builtin.import_tasks: post_tasks/end.yml
