---
- name: Python | Install
  ansible.builtin.apt:
    name:
      - pipx
      - python3
      - python3-pip
      - python3-venv
    state: present
  become: true

- name: Python | Install pipx packages
  community.general.pipx:
    name: "{{ item }}"
    state: present
  loop:
    - poetry
    - pre-commit
  become: true
