---
- name: Python | Install
  ansible.builtin.apt:
    name:
      - libssl-dev
      - python3
      - python3-pip
      - python3-venv
    state: present
  become: true

- name: Python | Install UV
  when:
    - python.uv.enable
  block:
    - name: UV | Install dependencies
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
        state: present
      become: true

    - name: UV | Detect previous install
      ansible.builtin.stat:
        path: "{{ ansible_home }}.local/bin/uv"
      register: uv

    - name: UV | Register state
      ansible.builtin.set_fact:
        uv_is_installed: "{{ uv.stat.exists }}"

    - name: UV | Install UV
      when:
        - not uv_is_installed
      block:
        - name: UV | Download UV install script
          ansible.builtin.get_url:
            url: https://astral.sh/uv/install.sh
            dest: /tmp/uv.install.sh
            force: true
            mode: "0755"

        - name: UV | Run the install script
          ansible.builtin.script:
            cmd: /tmp/uv.install.sh

    - name: UV | Install python packages
      when:
        - uv_is_installed
      block:
        - name: "UV | Install python 3.12"
          ansible.builtin.shell: |
            uv python install 3.12 --preview --default
          args:
            executable: /bin/bash
          failed_when: true
          changed_when: false

      rescue:
        - name: UV | Someting is wrong
          ansible.builtin.debug:
            msg: But I couldn't find what # TODO

- name: Python | Install Poetry
  when:
    - python.poetry.enable
  block:
    - name: Python | Install
      ansible.builtin.apt:
        name:
          - pipx
        state: present
      become: true

    - name: Python | Install pipx packages
      when:
        - ansible_distribution_major_version | int >= 22
      community.general.pipx:
        name: "{{ item }}"
        state: present
      loop:
        - ansible-lint
        - commitizen
        - ggshield
        - poetry
      become: true
