---
- name: SSH | Install packages
  ansible.builtin.apt:
    name:
      - openssh-client
      # - openssh-server
    state: present
  become: true

- name: SSH | Add additional SSH public keys
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ item }}"
  loop:
    - https://github.com/{{ git.user }}.keys

- name: SSH | Detect existing private key
  ansible.builtin.stat:
    path: "/mnt/c/Users/{{ windows_user }}/.ssh/{{ ssh.private_key }}"
  register: win_private_key

- name: SSH | Detect existing public key
  ansible.builtin.stat:
    path: "/mnt/c/Users/{{ windows_user }}/.ssh/{{ ssh.public_key }}"
  register: win_public_key

- name: SSH | Register state
  ansible.builtin.set_fact:
    win_private_key_is_installed: "{{ win_private_key.stat.exists }}"
    win_public_key_is_installed: "{{ win_public_key.stat.exists }}"

- name: SSH | Install Windows ssh key to WSL host
  when:
    - ansible_host_environment_is_wsl
    - win_private_key_is_installed
    - win_public_key_is_installed
  block:
    - name: SSH | Copy public key
      ansible.builtin.copy:
        src: "/mnt/c/Users/{{ windows_user }}/.ssh/{{ ssh.public_key }}"
        dest: "{{ ansible_home }}.ssh/{{ ssh.public_key }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0600"
    - name: SSH | Copy private key
      ansible.builtin.copy:
        src: "/mnt/c/Users/{{ windows_user }}/.ssh/{{ ssh.private_key }}"
        dest: "{{ ansible_home }}.ssh/{{ ssh.private_key }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0600"
