---
- name: "System | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: system_distribution_config

- name: "System | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: system_distribution_config.stat.exists

- name: System | Copy wsl config file
  ansible.builtin.copy:
    src: wsl.conf
    dest: /etc
    mode: "0644"
  when:
    - ansible_host_environment_is_wsl

- name: System | Copy Windows Terminal settings
  ansible.builtin.copy:
    src: settings.json
    dest: "/mnt/c/Users/{{ windows_user }}/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe"
    mode: "0644"
  when:
    - ansible_host_environment_is_wsl
