---
- name: System | Hostname | {{ ansible_distribution }}
  when:
    - not ansible_host_environment_is_wsl
  block:
    - name: System | Set hostname to inventory hostname
      ansible.builtin.hostname:
        name: "{{ hostname | default('ubuntu') }}"

    - name: System | Set /etc/hosts to include inventory hostname
      ansible.builtin.blockinfile:
        path: /etc/hosts
        block: |
          127.0.0.1  localhost
          {{ loop_host | default('127.0.1.1') }}  {{ hostname | default('ubuntu') }}

- name: System | {{ ansible_distribution }} | User
  when:
    - not ansible_host_environment_is_wsl
  block:
    - name: System | Ensure groups are present
      ansible.builtin.group:
        name: "{{ item }}"
        state: present
      loop:
        - sudo

    - name: System | Ensure sudo group has sudo privileges
      ansible.builtin.lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: ^%sudo
        line: "%sudo ALL=(ALL:ALL) ALL"
        validate: /usr/sbin/visudo -cf %s

    - name: System | Give sudo access to {{ ansible_user }}
      ansible.builtin.blockinfile:
        path: /etc/sudoers
        insertafter: "%sudo   ALL=(ALL:ALL) ALL"
        block: | # pragma: allowlist secret
          # Gives passwordless sudoer to user
          {{ ansible_user }}   ALL=(ALL)   NOPASSWD: ALL

- name: System | {{ ansible_distribution }} | Install packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - curl
    - git
    - nano
    - wget
  become: true

- name: System | {{ ansible_distribution }} | Install qemu-guest-agent
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - qemu-guest-agent
  become: true
  when:
    - not ansible_host_environment_is_wsl
    - ansible_virtualization_role == "guest"
  notify: Start qemu
