---
- name: "ZSH | Install dependencies"
  ansible.builtin.apt:
    name:
      - git
      - zsh
    state: present
  become: true

- name: "ZSH | Default shell"
  user:
    name: "{{ ansible_user }}"
    shell: "/usr/bin/zsh"
  become: true

- name: "ZSH | Detect oh-my-zsh"
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.oh-my-zsh"
  register: ohmyzsh

- name: "ZSH | Register oh-my-zsh state"
  ansible.builtin.set_fact:
    ohmyzsh_is_installed: "{{ ohmyzsh.stat.exists }}"

- name: "ZSH | Debug ohmyzsh_is_installed"
  ansible.builtin.debug:
    var: ohmyzsh

- name: "ZSH | Install oh-my-zsh"
  when: not ohmyzsh_is_installed
  block:
    - name: "ZSH | Download oh-my-zsh | Install Script"
      ansible.builtin.get_url:
        url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: "/tmp/oh-my-zsh.install.sh"
        force: true
        mode: "0755"
      notify: Cleanup oh-my-zsh

    - name: "ZSH | Run the install script"
      ansible.builtin.script:
        cmd: /tmp/oh-my-zsh.install.sh

- name: "ZSH | Install Nerds Fonts"
  block:
    - name: ZSH | Ensure fonts directory
      file:
        path: "/home/irish/.local/share/fonts"
        state: directory

    - name: ZSH | Download Hack fonts
      ansible.builtin.unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/Hack.zip
        dest: "/home/irish/.local/share/fonts/"
        remote_src: true
      notify: Update font-cache

- name: "ZSH | Setup oh-my-zsh plugin"
  block:
    - name: ZSH | Install powerlevel10k themes
      ansible.builtin.git:
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: ~/.oh-my-zsh/custom/themes/powerlevel10k
        depth: 1

    - name: ZSH | Install you-should-use plugin 
      ansible.builtin.git:
        repo: https://github.com/MichaelAquilina/zsh-you-should-use.git 
        dest: ~/.oh-my-zsh/custom/plugins/you-should-use
        depth: 1

    - name: ZSH | Install zsh-autosuggestions plugin
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
        depth: 1

    - name: ZSH | Install zsh-bat plugin
      ansible.builtin.git:
        repo: https://github.com/fdellwing/zsh-bat.git 
        dest: ~/.oh-my-zsh/custom/plugins/zsh-bat
        depth: 1

    - name: ZSH | Install zsh-exa plugin
      ansible.builtin.git:
        repo: https://github.com/ptavares/zsh-exa
        dest: ~/.oh-my-zsh/custom/plugins/zsh-exa
        depth: 1

    - name: ZSH | Install zsh-completions plugin
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-completions
        dest: ~/.oh-my-zsh/custom/plugins/zsh-completions
        depth: 1
    
    - name: ZSH | Install zsh-syntax-highlighting plugin
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
        depth: 1

    - name: ZSH | Install zsh-z plugin
      ansible.builtin.git:
        repo: https://github.com/agkozak/zsh-z
        dest: ~/.oh-my-zsh/custom/plugins/zsh-z
        depth: 1

- name: "ZSH | Copy .zshrc"
  ansible.builtin.copy:
    src: ".zshrc"
    dest: "/home/irish/.zshrc"
    mode: "0644"

- name: "ZSH | Copy .profile"
  ansible.builtin.copy:
    src: ".profile"
    dest: "/home/irish/.profile"
    mode: "0644"

- name: "ZSH | Copy .p10k.zsh"
  ansible.builtin.copy:
    src: ".p10k.zsh"
    dest: "/home/irish/.p10k.zsh"
    mode: "0644"
