---
- name: ZSH | Install dependencies
  ansible.builtin.apt:
    name:
      - bat
      - eza
      - fzf
      - git
      - unzip
      - zoxide
      - zsh
    state: present
  become: true

- name: ZSH | Default shell
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    shell: /usr/bin/zsh
  become: true

- name: ZSH | Detect oh-my-zsh
  ansible.builtin.stat:
    path: "{{ ansible_home }}/.oh-my-zsh"
  register: ohmyzsh

- name: ZSH | Register oh-my-zsh state
  ansible.builtin.set_fact:
    ohmyzsh_is_installed: "{{ ohmyzsh.stat.exists }}"

- name: ZSH | Debug ohmyzsh_is_installed
  ansible.builtin.debug:
    var: ohmyzsh

- name: ZSH | Install oh-my-zsh
  when:
    - not ohmyzsh_is_installed
  block:
    - name: ZSH | Download oh-my-zsh
      ansible.builtin.get_url:
        url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: /tmp/oh-my-zsh.install.sh
        force: true
        mode: "0755"
      notify: ZSH | Cleanup oh-my-zsh

    - name: ZSH | Run the install script
      ansible.builtin.script:
        cmd: /tmp/oh-my-zsh.install.sh
      become: true
      become_user: "{{ ansible_user }}"

- name: ZSH | Setup plugins
  block:
    - name: ZSH | Install powerlevel10k
      ansible.builtin.git:
        repo: https://github.com/romkatv/powerlevel10k.git
        version: v1.20.0
        dest: "{{ ansible_home }}/.oh-my-zsh/custom/themes/powerlevel10k"
        depth: 1

    - name: ZSH | Install you-should-use
      ansible.builtin.git:
        repo: https://github.com/MichaelAquilina/zsh-you-should-use.git
        version: 1.9.0
        dest: "{{ ansible_home }}/.oh-my-zsh/custom/plugins/you-should-use"
        depth: 1

    - name: ZSH | Install zsh-autosuggestions
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-autosuggestions
        version: v0.7.0
        dest: "{{ ansible_home }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
        depth: 1

    - name: ZSH | Install zsh-bat
      ansible.builtin.git:
        repo: https://github.com/fdellwing/zsh-bat.git
        version: c47f2de
        dest: "{{ ansible_home }}/.oh-my-zsh/custom/plugins/zsh-bat"
        depth: 1

    - name: ZSH | Install zsh-completions
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-completions
        version: 0.35.0
        dest: "{{ ansible_home }}/.oh-my-zsh/custom/plugins/zsh-completions"
        depth: 1

    - name: ZSH | Install zsh-eza
      ansible.builtin.git:
        repo: https://github.com/renovate-bot/z-shell-_-zsh-eza
        version: b0b0b02
        dest: "{{ ansible_home }}/.oh-my-zsh/custom/plugins/zsh-eza"
        depth: 1

    - name: ZSH | Install zsh-syntax-highlighting
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        version: 0.8.0
        dest: "{{ ansible_home }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
        depth: 1

    - name: ZSH | Install zsh-z
      ansible.builtin.git:
        repo: https://github.com/agkozak/zsh-z
        version: afaf29
        dest: "{{ ansible_home }}/.oh-my-zsh/custom/plugins/zsh-z"

    - name: ZSH | Fix permissions
      ansible.builtin.file:
        path: "{{ ansible_home }}/.oh-my-zsh/"
        mode: "0755"

- name: ZSH | Copy .zshrc
  ansible.builtin.copy:
    src: .zshrc
    dest: "{{ ansible_home }}/.zshrc"
    mode: "0644"

- name: ZSH | Copy .zsh_aliases
  ansible.builtin.copy:
    src: .zsh_aliases
    dest: "{{ ansible_home }}/.zsh_aliases"
    mode: "0644"
