---
# Orchestrator only: no module calls other than include_vars / include_tasks.

- name: Flux | Load release specific variables
  ansible.builtin.include_vars: "{{ fluxcd_vars_file }}"
  loop: "{{ query('ansible.builtin.first_found', fluxcd_vars_lookup) }}"
  loop_control:
    loop_var: fluxcd_vars_file
  vars:
    fluxcd_vars_lookup:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - "{{ role_path }}/vars"
      skip: true
  tags:
    - fluxcd
    - k8s

- name: Flux | Install
  ansible.builtin.include_tasks: "{{ fluxcd_install_tasks }}"
  vars:
    fluxcd_install_tasks: "{{ lookup('ansible.builtin.first_found', fluxcd_install_lookup) }}"
    fluxcd_install_lookup:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - "{{ role_path }}/tasks/install"
  tags:
    - fluxcd
    - k8s
    - install

- name: Flux | Verify
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/verify.yml"
  when: not ansible_check_mode
  tags:
    - fluxcd
    - k8s
    - verify
