---
- name: Flux | Install dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
    state: present
  become: true

- name: Flux | Detect flux
  ansible.builtin.stat:
    path: /usr/local/bin/flux
  register: fluxcd

- name: Flux | Register flux state
  ansible.builtin.set_fact:
    fluxcd_is_installed: "{{ fluxcd.stat.exists }}"

- name: Flux | Install fluxcd
  block:
    - name: Flux | Download flux install script
      ansible.builtin.get_url:
        url: https://fluxcd.io/install.sh
        dest: /tmp/fluxcd.install.sh
        force: true
        mode: "0755"

    - name: Flux | Run the install script
      ansible.builtin.script:
        cmd: /tmp/fluxcd.install.sh
