---
- name: ArgoCD | Install dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
    state: present
  become: true

- name: ArgoCD | Detect previous install
  ansible.builtin.stat:
    path: /usr/local/bin/argocd
  register: argocd

- name: ArgoCD | Register state
  ansible.builtin.set_fact:
    argocd_is_installed: "{{ argocd.stat.exists }}"
