---
- name: "Kubectl | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: system_distribution_config

- name: "Kubectl | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: system_distribution_config.stat.exists

- name: Kubectl | Configure .kube/config
  block:
    - name: K8s | Ensure .kube directory exists
      ansible.builtin.file:
        path: "{{ ansible_home }}/.kube"
        state: directory
        mode: "0755"
