---
- name: Kubectl  | Install dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
    state: present
  become: true

- name: Kubectl | Get latest kubectl version
  ansible.builtin.uri:
    url: https://dl.k8s.io/release/stable.txt
  register: kubectl_latest_version
  changed_when: false

- name: Kubectl | Adding Kubernetes GPG key
  ansible.builtin.apt_key:
    url: https://pkgs.k8s.io/core:/stable:/{{ kubectl_latest_version }}/deb/Release.key
    keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    state: present
  become: true

- name: Kubectl | Adding kubernetes apt repo
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/{{ kubectl_latest_version }} /deb/ /
    filename: kubernetes
    mode: "0644"
  become: true

- name: Kubectl | Installing Kubernetes
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - kubectl
  become: true

- name: K8s | Configure .kube/config
  block:
    - name: K8s | Ensure .kube directory exists
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.kube"
        state: directory
        mode: "0755"
