---
- name: Kubectl | Install dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
    state: present
  become: true

- name: Kubectl | Get latest kubectl version
  ansible.builtin.uri:
    url: https://dl.k8s.io/release/stable.txt
  register: kubectl_latest_release
  changed_when: false

- name: Kubectl | Add GPG key
  ansible.builtin.apt_key:
    url: https://pkgs.k8s.io/core:/stable:/{{ kubectl_latest_release }}/deb/Release.key
    keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    state: present
  become: true

- name: Kubectl | Add APT repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/{{ kubectl_latest_release }} /deb/ /
    filename: kubernetes
    mode: "0644"
  become: true

- name: Kubectl | Install packages
  ansible.builtin.apt:
    name:
      - kubectl
    state: present
  become: true
