---
- name: "Kubectl CLI  | Install dependencies"
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
    state: present
  become: true

- name: Kubectl CLI | Adding Kubernetes GPG key
  ansible.builtin.apt_key:
    url: "https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key"
    keyring: "/etc/apt/keyrings/kubernetes-apt-keyring.gpg"
    state: present
  become: true

- name: Kubectl CLI | Adding kubernetes apt repo
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /"
    filename: kubernetes
    mode: "0644"
  become: true

- name: Kubectl CLI | Installing Kubernetes
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - kubectl
  become: true

# - name: K8s | Configure .kube/config
#   block:
#     - name: K8s | Ensure .kube directory exists
#       ansible.builtin.file:
#         path: "~/.kube"
#         state: directory
#         mode: "0755"
#
#     - name: K8s | Copy .kube/config file
#       ansible.builtin.copy:
#         src: config
#         dest: "~/.kube/config"
#         mode: "0600"
