---
- name: "Git | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: system_distribution_config

- name: "Git | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: system_distribution_config.stat.exists

- name: Git | Global .gitignore file
  ansible.builtin.copy:
    src: .gitignore
    dest: "{{ ansible_home }}/.gitignore"
    mode: "0644"

- name: Git | Detect existing signing key
  ansible.builtin.stat:
    path: "{{ ansible_home }}.ssh/{{ git.signing_key }}"
  register: signing_key

- name: Git | Register state
  ansible.builtin.set_fact:
    signing_key_is_installed: "{{ signing_key.stat.exists }}"

- name: Git | Install signing key
  when:
    - signing_key_is_installed
  block:
    - name: Git | Read SSH key
      ansible.builtin.slurp:
        src: "{{ ansible_home }}/.ssh/{{ git.signing_key }}"
      register: ssh_key

    - name: Git | Add Allowed Signers
      ansible.builtin.blockinfile:
        path: "{{ ansible_home }}/.ssh/allowed_signers"
        mode: "0644"
        create: true
        block: |
          {{ git.email | default('email@exemple.com') }} {{ ssh_key.content | b64decode | default('ssh-ed25519 AAAA') }}

- name: Git | Create directories
  ansible.builtin.file:
    path: "{{ ansible_home }}/git/{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: "0700"
  loop:
    - "{{ git.user }}"

- name: Git | Update git configuration
  community.general.git_config:
    name: "{{ item.name }}"
    scope: file
    file: "{{ ansible_home }}/.gitconfig"
    value: "{{ item.value }}"
  with_items:
    - name: user.email
      value: "{{ git.email }}"
    - name: user.name
      value: "{{ git.name }}"
    - name: user.signingkey
      value: "{{ ansible_home }}.ssh/{{ git.signing_key }}"
    - name: user.user
      value: "{{ git.user }}"
    - name: advice.diverging
      value: false
    - name: branch.sort
      value: -committerdate
    - name: color.ui
      value: auto
    - name: column.ui
      value: auto
    - name: commit.gpgsign
      value: true
    - name: commit.verbose
      value: true
    - name: core.autocrlf
      value: false
    - name: core.editor
      value: code --wait
    - name: core.excludesfile
      value: "{{ ansible_home }}.gitignore"
    - name: credential.helper
      value: cache --timeout=3600
    - name: diff.algorithm
      value: histogram
    - name: diff.colorMoved
      value: zebra
    - name: fetch.all
      value: true
    - name: fetch.prune
      value: true
    - name: fetch.pruneTags
      value: true
    - name: fetch.writeCommitGraph
      value: true
    - name: gpg.format
      value: ssh
    - name: gpg.ssh.allowedSignersFile
      value: "{{ ansible_home }}.ssh/allowed_signers"
    - name: help.autocorrect
      value: prompt
    - name: init.defaultBranch
      value: main
    - name: log.abbrevCommit
      value: true
    - name: pull.ff
      value: only
    - name: pull.rebase
      value: true
    - name: push.autoSetupRemote
      value: true
    - name: push.default
      value: simple
    - name: push.followTags
      value: true
    - name: rebase.autoStash
      value: true
    - name: rerere.autoupdate
      value: true
    - name: rerere.enabled
      value: true
    - name: status.short
      value: true
    - name: tag.gpgsign
      value: true
    - name: tag.sort
      value: version:refname
