---
- name: "Git | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: system_distribution_config

- name: "Git | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: system_distribution_config.stat.exists

- name: Git | Computer Configuration
  block:
    - name: ZSH | Ensure git directory exist
      file:
        path: /home/irish/git
        state: directory

    - name: ZSH | Ensure irish1986 directory exist
      file:
        path: /home/irish/git/irish1986
        state: directory
