---
- name: "Git | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: system_distribution_config

- name: "Git | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: system_distribution_config.stat.exists

- name: Git | Update git configuration
  community.general.git_config:
    name: "{{ item.name }}"
    scope: file
    file: "{{ ansible_env.HOME }}/.gitconfig"
    value: "{{ item.value }}"
  with_items:
    - name: user.email
      value: "{{ git.email }}"
    - name: user.name
      value: "{{ git.name }}"
    - name: user.user
      value: "{{ git.user }}"
    - name: color.ui
      value: auto
    - name: commit.gpgsign
      value: false
    - name: commit.verbose
      value: true
    - name: credential.helper
      value: cache
    - name: core.autocrlf
      value: false
    - name: core.editor
      value: code --wait
    - name: diff.algorithm
      value: histogram
    - name: diff.colorMoved
      value: zebra
    - name: fetch.prune
      value: true
    - name: fetch.writeCommitGraph
      value: true
    - name: log.abbrevCommit
      value: true
    - name: init.defaultBranch
      value: main
    - name: pull.rebase
      value: true
    - name: push.default
      value: simple
    - name: push.autoSetupRemote
      value: true
    - name: rebase.autoStash
      value: true
    - name: rerere.autoupdate
      value: true
    - name: rerere.enabled
      value: true
    - name: status.short
      value: true
    - name: tag.gpgsign
      value: false
    - name: tag.sort
      value: version:refname
