---
- name: Git | Install git
  ansible.builtin.apt:
    name:
      - git
      - git-lfs
      - gh
    state: present
  become: true

# - name: Authenticate with GitHub using SSH key
#   command: gh auth login --hostname github.com --git-protocol ssh
