---
- name: Git | Install git | {{ ansible_distribution }}
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - git
    - git-lfs
  become: true

- name: Git | Install GitHub CLI tool | {{ ansible_distribution }}
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - gh
  become: true

# - name: Authenticate with GitHub using SSH key
#   command: gh auth login --hostname github.com --git-protocol ssh
