---
- name: Obsidian | Download Latest Version JSON
  ansible.builtin.uri:
    url: https://api.github.com/repos/obsidianmd/obsidian-releases/releases/latest
  register: obsidian_latest_version_json
  changed_when: false

- name: Obsidian | Registering Latest Release
  ansible.builtin.set_fact:
    obsidian_latest_release: "{{ obsidian_latest_version_json.json.tag_name }}"

- name: Obsidian | Registering Latest Version
  ansible.builtin.set_fact:
    obsidian_latest_version: "{{ obsidian_latest_version_json.stdout | default('') }}"

- name: Obsidian | Show obsidian_latest_version debug
  ansible.builtin.debug:
    var: obsidian_latest_release

- name: Obsidian | Clone Obsidian Git Repo
  ansible.builtin.git:
    repo: "{{ obsidian.repository }}"
    dest: "{{ ansible_env.HOME }}/{{ obsidian.directory }}"
    depth: 1

- name: Obsidian | Create Cron Job to Pull, Commit, and Push to Git
  ansible.builtin.cron:
    name: Git Pull, Commit, and Push
    minute: "*"
    job: cd {{ ansible_env.HOME }}/{{ obsidian.directory }} && git pull && git add -A && git commit -m 'Auto backup from $HOSTNAME' && git push
  become: true
