---
- name: Obsidian | Download Latest Version JSON
  ansible.builtin.uri:
    url: https://api.github.com/repos/obsidianmd/obsidian-releases/releases/latest
  register: obsidian_latest_version_json
  changed_when: false

- name: Obsidian | Registering Latest Release
  ansible.builtin.set_fact:
    obsidian_latest_release: "{{ obsidian_latest_version_json.json.tag_name }}"

- name: Obsidian | Show obsidian_latest_version debug
  ansible.builtin.debug:
    var: obsidian_latest_release
