---
- name: "GGShield | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: fastfetch_distribution_config

- name: "GGShield | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: fastfetch_distribution_config.stat.exists

- name: GGShield | Ensure .config directory exists
  ansible.builtin.file:
    path: "{{ ansible_home }}/{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - .config
    - .config/ggshield

- name: GGShield | Copy config file
  ansible.builtin.copy:
    src: auth_config.yaml
    dest: "{{ ansible_home }}/.config/ggshield"
    mode: "0644"
