---
- name: "Tmux | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: system_distribution_config

- name: "Tmux | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: system_distribution_config.stat.exists

- name: Tmux | Configure tmux
  ansible.builtin.copy:
    src: tmux.conf
    dest: "{{ ansible_home }}/.config/tmux/"
    mode: "0644"
    directory_mode: "0755"
    force: true
