---
- name: Tmux | Install tmux
  ansible.builtin.apt:
    name:
      - tmux
    state: present
  become: true

- name: Tmux | Ensure .config directory exists
  ansible.builtin.file:
    path: "{{ ansible_home }}/{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - .config
    - .config/tmux/plugins/tpm

- name: Tmux | Install TPM
  block:
    - name: Tmux | Install TPM
      ansible.builtin.git:
        repo: https://github.com/tmux-plugins/tpm
        version: v3.1.0
        dest: ~/.config/tmux/plugins/tpm
