---
- name: Tmux | Install tmux
  ansible.builtin.apt:
    name:
      - tmux
    state: present
  become: true

- name: Tmux | Ensure .config directory exists
  ansible.builtin.file:
    path: "{{ ansible_home }}/{{ item }}"
    state: directory
    recurse: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  loop:
    - .config
    - .config/tmux/plugins/tpm

- name: Tmux | Install TPM
  block:
    - name: Tmux | Install TPM
      ansible.builtin.git:
        repo: https://github.com/tmux-plugins/tpm
        version: 7bdb7ca
        dest: "{{ ansible_home }}/.config/tmux/plugins/tpm"
        depth: 1
