---
secrets_script_path: "{{ dotfiles_home }}/.local/bin/dotfiles-secrets"
secrets_config_file: "{{ dotfiles_home }}/.config/dotfiles/secrets.conf"
secrets_local_dir: "{{ dotfiles_home }}/.config/dotfiles/secrets"
secrets_credentials_file: "{{ dotfiles_home }}/.config/infisical/universal-auth"
secrets_zshenv: "{{ dotfiles_home }}/.zshenv"

secrets_has_targets: "{{ secrets_targets | length > 0 }}"
secrets_use_infisical: "{{ secrets_source == 'infisical' }}"
secrets_has_shell_target: "{{ secrets_targets | selectattr('dest', 'eq', 'shell') | list | length > 0 }}"
