---
- name: "fastfetch | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: fastfetch_distribution_config

- name: "fastfetch | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: fastfetch_distribution_config.stat.exists

- name: fastfetch | {{ ansible_distribution }} | Ensure .config directory exists
  ansible.builtin.file:
    path: /home/irish/{{ item }}
    state: directory
    mode: "0755"
  loop:
    - .config
    - .config/fastfetch

- name: fastfetch | {{ ansible_distribution }} | Remove neofetch thx for your service
  ansible.builtin.file:
    path: /home/irish/.config/neofetch
    state: absent

- name: fastfetch | {{ ansible_distribution }} | Copy config file
  ansible.builtin.copy:
    src: config.jsonc
    dest: /home/irish/.config/fastfetch
    mode: "0644"
