---
- name: "Fastfetch | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: fastfetch_distribution_config

- name: "Fastfetch | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: fastfetch_distribution_config.stat.exists

- name: Fastfetch | Ensure .config directory exists
  ansible.builtin.file:
    path: "{{ ansible_home }}/{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - .config
    - .config/fastfetch

- name: Fastfetch | Remove neofetch thx for your service
  ansible.builtin.file:
    path: "{{ ansible_home }}/.config/neofetch"
    state: absent

- name: Fastfetch | Copy config file
  ansible.builtin.copy:
    src: config.jsonc
    dest: "{{ ansible_home }}/.config/fastfetch"
    mode: "0644"
