---
- name: ZSH | Remove oh-my-zsh script
  ansible.builtin.file:
    path: /tmp/oh-my-zsh.install.sh
    state: absent

- name: ZSH | Cleanup oh-my-zsh
  ansible.builtin.file:
    path: /home/irish/oh-my-zsh.install.sh
    state: absent
