---
- name: Remove oh-my-zsh Script
  ansible.builtin.file:
    path: /tmp/oh-my-zsh.install.sh
    state: absent

- name: Cleanup oh-my-zsh
  ansible.builtin.file:
    path: /{{ ansible_user_dir }}/oh-my-zsh.install.sh
    state: absent

- name: Update font-cache 
  ansible.builtin.command: fc-cache -fv
