---
- name: Timezone | Remove systemd-timesyncd packages
  ansible.builtin.apt:
    name:
      - systemd-timesyncd
    state: absent
  become: true

- name: Timezone | Install package
  ansible.builtin.apt:
    name:
      - ntp
    state: present
  become: true
  notify: Timezone | Start ntp

- name: Timezone | Set local timezone
  community.general.timezone:
    name: "{{ timezone.locale | default('Etc/UTC') }}"
