---
# Variable configuration.
- include_tasks: variables.yml

- name: "System | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: system_distribution_config

- name: "System | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: system_distribution_config.stat.exists

- name: Install unattended-upgrades
  ansible.builtin.include_tasks: unattended-upgrades.yml
- name: Install packages
  ansible.builtin.include_tasks: packages.yml
- name: Configure users
  ansible.builtin.include_tasks: user.yml
- name: Disable cloud-init
  ansible.builtin.include_tasks: cloud-init.yml
