---
- name: Docker | Install dependencies
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
  become: true

- name: Docker | Add GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    keyring: /etc/apt/keyrings/docker.gpg
    state: present
  become: true

- name: Docker | Get System Architecture
  ansible.builtin.command: dpkg --print-architecture
  register: dpkg_architecture
  changed_when: false
  failed_when: false
  check_mode: false

- name: Docker | Add APT repository
  ansible.builtin.apt_repository:
    repo: |
      deb [arch={{ dpkg_architecture.stdout }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    filename: docker
    mode: "0644"
  become: true

- name: Docker | Install packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  become: true

- name: Docker | Enable service
  ansible.builtin.systemd:
    enabled: true
    name: docker
    state: started
  become: true
  when:
    - not ansible_host_environment_is_wsl

- name: Docker | Add to group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
  become: true

- name: Docker | Ensure docker data directory exists
  ansible.builtin.file:
    path: "{{  ansible_user_dir }}/.local/lib/docker"
    state: directory
    mode: "0710"
  become: true

- name: Docker | Copy daemon.json
  ansible.builtin.template:
    dest: /etc/docker/daemon.json
    src: daemon.json
    mode: "0644"
  become: true
  notify: Restart Docker
