---
- name: Precommit | Install
  ansible.builtin.apt:
    name:
      - pipx
      - python3
      - python3-pip
      - python3-venv
    state: present
  become: true

- name: Precommit | Install pipx packages
  when:
    - ansible_distribution_major_version | int >= 22
  community.general.pipx:
    name: "{{ item }}"
    state: present
  loop:
    - pre-commit
  become: true
