---
- name: VPNKit | Install dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
    state: present
  become: true

- name: "VPNKit | Copy config file "
  ansible.builtin.copy:
    src: wsl-vpnkit.service
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: "0644"

- name: VPNKit | Enable and check wsl-vpnkit service
  ansible.builtin.systemd:
    name: wsl-vpnkit
    daemon_reload: true
    state: restarted
    enabled: true
