---
# - name: Detect Windows Current User
#   ansible.builtin.shell:
#     cmd: $env:UserName
#   register: windows_user
#   changed_when: false
#   failed_when: windows_user.rc != 0
#   args:
#     executable: powershell.exe
#   when:
#     - ansible_host_environment_is_wsl

# - name: Register Windows Current User
#   ansible.builtin.set_fact:
#     wsl_host_user: "{{ windows_user.stdout }}"
#   when:
#     - ansible_host_environment_is_wsl
#     - host_user is not defined

# - name: DEBUG
#   ansible.builtin.debug:
#     msg: "wsl_host_user: {{ wsl_host_user }}"
#   when:
#     - ansible_host_environment_is_wsl

- name: Register Current User
  ansible.builtin.set_fact:
    host_user: "{{ ansible_env['USER']}}"
  when:
    - host_user is not defined
