---
- name: "Btop | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: btop_distribution_config

- name: "Btop | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: btop_distribution_config.stat.exists

- name: Btop | Ensure .config directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - .config
    - .config/btop

- name: Btop | Copy config file
  ansible.builtin.copy:
    src: btop.conf
    dest: "{{ ansible_env.HOME }}/.config/btop/"
    mode: "0644"
