---
- name: "btop | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: btop_distribution_config

- name: "btop | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: btop_distribution_config.stat.exists

- name: btop | {{ ansible_distribution }} | Ensure .config directory exists
  ansible.builtin.file:
    path: /home/irish/{{ item }}
    state: directory
    mode: "0755"
  loop:
    - .config
    - .config/btop

- name: btop | {{ ansible_distribution }} | Copy config file
  ansible.builtin.copy:
    src: btop.conf
    dest: /home/irish/.config/btop/
    mode: "0644"
