---
- name: Btop | Install btop
  ansible.builtin.apt:
    name:
      - btop
    state: present
  become: true

- name: Btop | Remove htop thx for your service
  ansible.builtin.apt:
    name:
      - htop
    state: absent
  become: true
