---
- name: btop | Ubuntu | Install btop
  ansible.builtin.apt:
    name: btop
    state: present
  become: true

- name: btop | Ubuntu | Remove htop thx for your service
  ansible.builtin.apt:
    name: htop
    state: absent
  become: true
