---
- name: Update | Restart unattended-upgrades
  ansible.builtin.systemd_service:
    name: "{{ update_unattended_service }}"
    enabled: true
    state: restarted
  become: true
  when: dotfiles_has_systemd | bool
