---
- name: Start unattended-upgrades
  ansible.builtin.systemd:
    name: unattended-upgrades
    state: started
- name: Reboot
  ansible.builtin.reboot:
    msg: Rebooting nodes
    reboot_timeout: 3600
    test_command: uptime
- name: Restart unattended-upgrades
  ansible.builtin.service:
    name: unattended-upgrades.service
    daemon_reload: true
    enabled: true
    state: restarted
