---
- name: "Neovim | {{ ansible_distribution }} | Dependencies"
  ansible.builtin.apt:
    name:
      - ansible-lint
      - cmake
      - curl
      - libtool
      - pkg-config
      - ripgrep
      - unzip
    state: present
  become: true

- name: "Neovim | {{ ansible_distribution }} | Install"
  ansible.builtin.apt_repository:
    repo: ppa:neovim-ppa/unstable
    state: present
  become: true
