---
- name: Neovim | Install dependencies
  ansible.builtin.apt:
    name:
      - ansible-lint
      - cmake
      - curl
      - libtool
      - pkg-config
      - ripgrep
      - unzip
    state: present
  become: true

- name: Neovim | Install packages
  ansible.builtin.apt_repository:
    repo: ppa:neovim-ppa/unstable
    state: present
  become: true
