---
default_roles:
  - btop
  - fastfetch
  - git
  - system
  - timezone
  - update
  - zsh

exclude_roles:
  - docker
  - fluxcd
  - gh
  - helm
  - k9s
  - kind
  - kubectl
  - neovim
  - nvm
  - obsidian
  - powershell
  - python
  - ssh
  - taskfile
  - terraform
  - tmux
  - ufw
  - vscode

# Role - System Variables
ansible_user: irish
loop_host: 127.0.1.1
hostname: ubuntu-wsl

# Role - Timezone Variables
system_timezone: America/Toronto

# Role - Git Variables
git_user_name: Simon Harvey
git_user_user: irish1986
git_user_email: simon.harvey.86@gmail.com

# Role - SSH Variables
github_ssh_keys: https://github.com/irish1986.keys
launchpad_ssh_keys: ""
other_ssh_keys: ""

# Role - ZSH Variables
zsh_fonts: Hack
