---
default_roles:
  - btop
  - cloud-init
  - fastfetch
  - fonts
  - git
  - system
  - timezone
  - tmux
  - update
  - zsh

exclude_roles:
  - docker
  - fluxcd
  - helm
  - k9s
  - kind
  - kubectl
  - neovim
  - nvm
  - obsidian
  - powershell
  - python
  - ssh
  - terraform
  - ufw
  - vpnkit
  - vscode

# Role - System Variables
ansible_user: username
loop_host: 127.0.1.1
hostname: ubuntu-wsl

# Role - Docker Variables
docker:
  enable: true
  network: 172.10.0.0

# Role - Git Variables
git:
  directory:
    - personal
    - reference
    - work
  email: email@example.com
  name: John Doe
  user: username

# Role - Fonts Variables
fonts:
  nf: Nerd

# Role - Obsidian Variables
obsidian:
  repository: " git@github.com:user/notes.git"
  directory: " .notes"

# Role - SSH Variables
ssh:
  github: ""
  launchpad: ""
  other: ""

# Role - Timezone Variables
timezone:
  locale: America/Toronto

# Role - ZSH Variables
zsh:
  fonts: Hack
