---
# Role - System Variables
secret_bws_access_token: "{{ lookup('env', 'BWS_ACCESS_TOKEN') }}"

# Role - System Variables
ansible_user: username
ansible_home: /home/{{ ansible_user }}/
loop_host: 127.0.1.1
hostname: ubuntu-wsl

# Role - Docker Variables
docker:
  enable: true
  network: 172.10.0.0

# Role - Git Variables
git:
  dir:
    personal:
    reference:
    work:
  email: email@example.com
  name: John Doe
  user: username

# Role - Fonts Variables
fonts:
  nf: Nerd

# Role - Notes Variables
notes:
  repository: "https://github.com/irish1986/notes"
  directory: " .notes"

# Role - SSH Variables
ssh:
  github: ""
  launchpad: ""
  other: ""

# Role - Timezone Variables
timezone:
  locale: America/Toronto

# Role - ZSH Variables
zsh:
  fonts: Hack
