---
name: Continous Integration

on: # yamllint disable-line rule:truthy
  pull_request:
  push:
    paths-ignore:
      - '**/README.md'

jobs:

  pre-commit:
    uses: ./.github/workflows/pre-commit.yml
  secret:
    uses: ./.github/workflows/secret.yml
