---
name: Continous Integration - Labeler

on:
  workflow_dispatch:
  pull_request_target:
    branches: ["main"]

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Labeler
        uses: actions/labeler@v5.0.0
        with:
          repo-token: "${{ steps.app-token.outputs.token }}"
          configuration-path: .github/labeler.yaml
