---
name: Continous Integration - Label Sync

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - ".github/labels.yml"
  schedule:
    - cron: "0 0 * * *" # Every day at midnight
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  issues: write

jobs:
  label-sync:
    name: Label Sync
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          sparse-checkout: .github/labels.yml

      - name: Sync Labels
        uses: EndBug/label-sync@v2
        with:
          config-file: .github/labels.yml
          delete-other-labels: true
