---
name: Continous Integration - Labeler

on: # yamllint disable-line rule:truthy
  pull_request_target:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN_SECRET }}
  OWNER: ${{ github.event.issue.user.login }}
  REPO: ${{ github.event.repository.name }}
  ISSUE_NUMBER: ${{ github.event.issue.number }}

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Labeler
        uses: actions/labeler@v5.0.0
        with:
          repo-token: "${{ steps.app-token.outputs.token }}"
          configuration-path: .github/labeler.yml
          sync-labels: true
          dot: true
