---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Label Sync"

on: # yamllint disable-line rule:truthy
  push:
    branches: ["main"]
    paths: [".github/labels.yml"]
  schedule:
    - cron: "0 0 * * *" # Every day at midnight
  workflow_dispatch:

permissions:
  issues: write

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  label-sync:
    name: GitHub Label Sync
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github/labels.yml

      - name: Sync Labels
        uses: EndBug/label-sync@v2
        with:
          config-file: .github/labels.yml
          delete-other-labels: true
