---
name: Continous Integration - Main

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  main:
    name: Main Workflow
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

  # pre-commit:
  #   uses: ./.github/workflows/pre-commit.yml
  # secret:
  #   uses: ./.github/workflows/secret.yml
